package pck;
// Generated 2016-1-3 15:54:18 by Hibernate Tools 4.3.1



/**
 * AdminInfo generated by hbm2java
 */
public class AdminInfo  implements java.io.Serializable {


     private String adminName;
     private String password;

    public AdminInfo() {
    }

	
    public AdminInfo(String adminName) {
        this.adminName = adminName;
    }
    public AdminInfo(String adminName, String password) {
       this.adminName = adminName;
       this.password = password;
    }
   
    public String getAdminName() {
        return this.adminName;
    }
    
    public void setAdminName(String adminName) {
        this.adminName = adminName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


