package pck;
// Generated 2016-1-3 15:54:18 by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * Batch generated by hbm2java
 */
public class Batch  implements java.io.Serializable {


     private String batchNum;
     private String teacherName;
     private Serializable startDate;
     private Serializable endDate;
     private Integer capacity;

    public Batch() {
    }

	
    public Batch(String batchNum) {
        this.batchNum = batchNum;
    }
    public Batch(String batchNum, String teacherName, Serializable startDate, Serializable endDate, Integer capacity) {
       this.batchNum = batchNum;
       this.teacherName = teacherName;
       this.startDate = startDate;
       this.endDate = endDate;
       this.capacity = capacity;
    }
   
    public String getBatchNum() {
        return this.batchNum;
    }
    
    public void setBatchNum(String batchNum) {
        this.batchNum = batchNum;
    }
    public String getTeacherName() {
        return this.teacherName;
    }
    
    public void setTeacherName(String teacherName) {
        this.teacherName = teacherName;
    }
    public Serializable getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Serializable startDate) {
        this.startDate = startDate;
    }
    public Serializable getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Serializable endDate) {
        this.endDate = endDate;
    }
    public Integer getCapacity() {
        return this.capacity;
    }
    
    public void setCapacity(Integer capacity) {
        this.capacity = capacity;
    }




}


