package pck;
// Generated 2016-1-3 15:54:18 by Hibernate Tools 4.3.1



/**
 * Html5 generated by hbm2java
 */
public class Html5  implements java.io.Serializable {


     private String hid;
     private String question;
     private String options;
     private String keys;

    public Html5() {
    }

	
    public Html5(String hid) {
        this.hid = hid;
    }
    public Html5(String hid, String question, String options, String keys) {
       this.hid = hid;
       this.question = question;
       this.options = options;
       this.keys = keys;
    }
   
    public String getHid() {
        return this.hid;
    }
    
    public void setHid(String hid) {
        this.hid = hid;
    }
    public String getQuestion() {
        return this.question;
    }
    
    public void setQuestion(String question) {
        this.question = question;
    }
    public String getOptions() {
        return this.options;
    }
    
    public void setOptions(String options) {
        this.options = options;
    }
    public String getKeys() {
        return this.keys;
    }
    
    public void setKeys(String keys) {
        this.keys = keys;
    }




}


