package pck;
// Generated 2016-1-3 15:54:18 by Hibernate Tools 4.3.1



/**
 * Java01 generated by hbm2java
 */
public class Java01  implements java.io.Serializable {


     private int jid;
     private String question;
     private String options;
     private String keys;

    public Java01() {
    }

	
    public Java01(int jid) {
        this.jid = jid;
    }
    public Java01(int jid, String question, String options, String keys) {
       this.jid = jid;
       this.question = question;
       this.options = options;
       this.keys = keys;
    }
   
    public int getJid() {
        return this.jid;
    }
    
    public void setJid(int jid) {
        this.jid = jid;
    }
    public String getQuestion() {
        return this.question;
    }
    
    public void setQuestion(String question) {
        this.question = question;
    }
    public String getOptions() {
        return this.options;
    }
    
    public void setOptions(String options) {
        this.options = options;
    }
    public String getKeys() {
        return this.keys;
    }
    
    public void setKeys(String keys) {
        this.keys = keys;
    }




}


