package pck;
// Generated 2016-1-3 15:54:18 by Hibernate Tools 4.3.1



/**
 * Performance generated by hbm2java
 */
public class Performance  implements java.io.Serializable {


     private String registerNum;
     private String practiceName;
     private Integer score;

    public Performance() {
    }

	
    public Performance(String registerNum, String practiceName) {
        this.registerNum = registerNum;
        this.practiceName = practiceName;
    }
    public Performance(String registerNum, String practiceName, Integer score) {
       this.registerNum = registerNum;
       this.practiceName = practiceName;
       this.score = score;
    }
   
    public String getRegisterNum() {
        return this.registerNum;
    }
    
    public void setRegisterNum(String registerNum) {
        this.registerNum = registerNum;
    }
    public String getPracticeName() {
        return this.practiceName;
    }
    
    public void setPracticeName(String practiceName) {
        this.practiceName = practiceName;
    }
    public Integer getScore() {
        return this.score;
    }
    
    public void setScore(Integer score) {
        this.score = score;
    }




}


