package pck;
// Generated 2016-1-3 15:54:18 by Hibernate Tools 4.3.1



/**
 * Practice generated by hbm2java
 */
public class Practice  implements java.io.Serializable {


     private String practiceName;
     private String adminName;

    public Practice() {
    }

	
    public Practice(String practiceName) {
        this.practiceName = practiceName;
    }
    public Practice(String practiceName, String adminName) {
       this.practiceName = practiceName;
       this.adminName = adminName;
    }
   
    public String getPracticeName() {
        return this.practiceName;
    }
    
    public void setPracticeName(String practiceName) {
        this.practiceName = practiceName;
    }
    public String getAdminName() {
        return this.adminName;
    }
    
    public void setAdminName(String adminName) {
        this.adminName = adminName;
    }




}


