package pck;
// Generated 2016-1-3 15:54:18 by Hibernate Tools 4.3.1



/**
 * Student generated by hbm2java
 */
public class Student  implements java.io.Serializable {


     private String registerNum;
     private String batchNum;
     private String enName;
     private String chName;
     private String password;

    public Student() {
    }

	
    public Student(String registerNum) {
        this.registerNum = registerNum;
    }
    public Student(String registerNum, String batchNum, String enName, String chName, String password) {
       this.registerNum = registerNum;
       this.batchNum = batchNum;
       this.enName = enName;
       this.chName = chName;
       this.password = password;
    }
   
    public String getRegisterNum() {
        return this.registerNum;
    }
    
    public void setRegisterNum(String registerNum) {
        this.registerNum = registerNum;
    }
    public String getBatchNum() {
        return this.batchNum;
    }
    
    public void setBatchNum(String batchNum) {
        this.batchNum = batchNum;
    }
    public String getEnName() {
        return this.enName;
    }
    
    public void setEnName(String enName) {
        this.enName = enName;
    }
    public String getChName() {
        return this.chName;
    }
    
    public void setChName(String chName) {
        this.chName = chName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


